### ISSUE TITLE
NOTE: This project is in a severe backlog, I will get back to it when I actually learn C++ and CSS and stuff

### ISSUE THREAD

**Issue by ABSanthosh** [Arjdroid/ColorPicker#1]
Hey!

Any plan on continuing this project?

**Comment by Arjdroid** [comment]
> Hey!
> 
> Any plan on continuing this project?

Hello! unfortunately due to my current situation I will not be working on this project for atleast many months. 

I am glad to see that there are other people who are also interested in such an application.

If you are interested in acquiring similar functionality as of now, I would recommend using the open source gpick http://www.gpick.org/ program which I have mentioned in this project as it has all of the functionality (color picker and showing similar color pallette and showing hex/RGB/HSV/HSL values, etc.) Of the aforementioned Microsoft Power Toys Color Picker program on Linux although, admittedly, its UI / UX is not as beautiful. 

I believe that Gpick is packaged for many popular Linux distributions such as Arch Linux, Pop OS, etc. In case it is not packaged for your distribution, you can also it compile it using the instructions on their GitHub repository, https://github.com/thezbyg/gpick

**Comment by ABSanthosh** [comment]
That’s unfortunate.

Since I switched to Linux recently and I’m missing a lot of windows applications like Powertoys color picker, sticky notes, Ueli(https://ueli.app/) and instead of looking for similar apps, I’m planning to build them. Already started with sticky notes l.

If you’re interested in collaborating, let me know, that would be great.

**Comment by Arjdroid** [comment]
Interesting, what distro (and DE / WM) are you using, if you don't mind my asking? As an alternative to Ueli, (I use Launchy on Windows) I use the Pop Launcher on Linux (from Pop!_OS) I am using Arch Linux with GNOME and Pop Launcher works with GNOME because its a GNOME Shell Extension, it is a great launcher and if you are using GNOME, I highly recommend you look into it. I believe KDE already has a built in launcher and I am not aware much about other Linux Desktop configurations...

A lot of the Powertoys tools are pretty useful but their functionalities can be brought to Linux:

- Instead of Color Picker, I use gpick
- Instead of FancyZones, I use Pop Shell Extension which has Auto Tiling Built-In
- Instead of File Explorer Preview, I use double clicking the file lol
- Instead of image resizer, I use GIMP or I use imagemagick, which are less convenient but they get the job done
- Instead of Keyboard Manager, I use GNOME Tweaks
- I don't use Power Rename
- Instead of PowerToys Run / Uebli / Launchy, I use the Pop Launcher
- I don't use SHortcut Guide

I don't know what exactly is Sticky Notes app but some good Note Taking apps I know are Joplin and even just using Markdown in Atom editor (alternative to VSCode, owned by Microsoft / Github)

GNOME's built in Screenshot tool is also pretty useful.

Pop!_OS is the first desktop Linux desktop distro I installed and I highly recommend it as it is easy to use and has a lot of great features and alternatives to windows apps and stuff.

**Comment by ABSanthosh** [comment]
I started with ubuntu but I had to switch back to windows because of a anti-cheat browser from my uni. It wouldn't even work on virtual machines. Now I'm using Zorin OS with GNOME and x11. Its pretty basic though.

Pop launcher sounds good. I'll definitely look into that. 

The only powertoy that I use frequently is the color picker(I'm a frontend dev for the most part and I'll need the color from a window or image or whatever very often. I did try to find linux alternatives for the utilities I had in windows but the UI part is very off putting in the linux counterparts. That's why I decided to build them on my own.

Sticky notes is basically like physical sticky notes. You make a sticky note and it stays on top of all windows(Even after reboot) till you close it. 

One of the main feature that I'm missing from windows is the clipboard history. As a programmer, It was sooo handy. yet to find a reliable alternative to it.

I did try Pop!_OS but for me, It felt very cluttered and I didn't have the time to customise it to my liking. Zorin OS comes with a set of pre-built layouts and is pretty minimal. Check it out if you're planning to try other distros!
